- name: Wait for apt lock release
  become: true
  shell: |
    for i in {1..60}; do
      fuser /var/lib/dpkg/lock-frontend >/dev/null 2>&1 || exit 0
      sleep 2
    done
    exit 1
  args:
    executable: /bin/bash
  register: apt_lock
  failed_when: apt_lock.rc != 0
  changed_when: false
  
- name: Install base packages without apt update
  apt:
    name:
      - curl
      - git
      - htop
      - net-tools
    state: present
    update_cache: false

- name: Check - curl, git, htop, net-tools
  shell: |
    curl --version >/dev/null \
    && git --version >/dev/null \
    && htop --version >/dev/null \
    && netstat --version >/dev/null
  register: base_tools_check
  changed_when: false
  failed_when: base_tools_check.rc != 0

- name: Install Python library for Kubernetes management
  apt:
    name: python3-kubernetes
    state: present

- name: Verify that kubernetes module is available for Python
  ansible.builtin.command: python3 -c "import kubernetes"
  changed_when: false
  failed_when: false
  register: k8s_module_check

- name: Show result of kubernetes module check
  ansible.builtin.debug:
    var: k8s_module_check.stderr

- name: Install kustomize via snap
  shell: |
    if ! command -v kustomize &> /dev/null; then
      sudo snap install kustomize
    fi
  tags: [packages]
