title = "Gitleaks config"

[allowlist]
description = "Allow common false positives"
paths = [
  ".git/",
  "node_modules/",
  "dist/"
]

[rules]
[[rules]]
id = "generic-secret-assignment"
description = "Generic secret assignment"
regex = '''(?i)(password|secret|token|api[_-]?key)\s*[:=]\s*['"]?[A-Za-z0-9\-\._]{10,}['"]?'''
tags = ["secret","generic"]
