repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v4.6.0
  hooks:
  - id: check-yaml
  - id: end-of-file-fixer
  - id: trailing-whitespace

- repo: https://github.com/adrienverge/yamllint
  rev: v1.35.1
  hooks:
  - id: yamllint

- repo: https://github.com/returntocorp/semgrep
  rev: v1.92.0
  hooks:
  - id: semgrep
    args: ["--config", "semgrep/semgrep.yml", "--json"]

- repo: https://github.com/gitleaks/gitleaks
  rev: v8.18.4
  hooks:
  - id: gitleaks
    args: ["detect", "--config", ".gitleaks.toml", "--no-banner"]

- repo: https://github.com/bridgecrewio/checkov
  rev: 3.2.333
  hooks:
  - id: checkov
    args: ["-d", ".github/workflows", "--framework", "github_actions"]
