title = "gitleaks config"

[allowlist]
description = "allow common test strings"
regexes = [
  '''(?i)example|dummy|testkey|notasecret'''
]

[[rules]]
description = "Generic credentials"
id = "generic-cred"
regex = '''(?i)(secret|token|password|passwd|access[_-]?key|secret[_-]?key)\s*[:=]\s*['"]?[A-Za-z0-9/_\-+=]{16,}['"]?'''
tags = ["credential","generic"]
