- name: Create argocd-secret with GitHub clientSecret
  kubernetes.core.k8s:
    state: present
    namespace: "{{ argocd_namespace }}"
    definition:
      apiVersion: v1
      kind: Secret
      metadata:
        name: argocd-secret
      stringData:
        github.clientSecret: "{{ github_oauth_client_secret }}"
